### ISSUE TITLE
Error: missing required field "serviceName"

### ISSUE THREAD

**Issue by marquesds** [riskfocus/helm-charts-public#3]
Hi! I'm trying to install Flink on my Kubernetes cluster with this command:
`helm install my-flink --namespace my-namespace riskfocus/flink --version 0.1.9`

And I'm receiving the error below:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec
```

How can I get rid from this error?

**Comment by vkropotko** [comment]
Hi @marquesds!

It was an issue in this version. Fixed in 0.1.10.

**Comment by marquesds** [comment]
@vkropotko I've tried to install the `0.1.10` version but I'm still having an error, not the same as above, but the error below:

```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
```
